using RecadastramentoApi.DTO;

namespace RecadastramentoApi.Models;

public static class PersonaMappings
{
    public static PersonaResponseDto ToResponseDto(this Persona persona)
    {
        return new PersonaResponseDto
        {
            Id = persona.Id,
            FkRecadastramento = persona.FkRecadastramento,
            Nome = persona.Nome,
            NomeSocial = persona.NomeSocial,
            Fonetico = persona.Fonetico,
            Cpf = persona.Cpf,
            Pasep = persona.Pasep,
            DataNascimento = persona.DataNascimento,
            DataFalecimento = persona.DataFalecimento,
            Mae = persona.Mae,
            Pai = persona.Pai,
            SexoEnum = persona.SexoEnum,
            EtniaEnum = persona.EtniaEnum,
            Ddd = persona.Ddd,
            Telefone = persona.Telefone,
            Telefone2 = persona.Telefone2,
            EMail = persona.EMail,
            Nit = persona.Nit,
            Nis = persona.Nis,
            NacionalidadeEnum = persona.NacionalidadeEnum,
            NacionalidadePais = persona.NacionalidadePais,
            NaturalidadeId = persona.NaturalidadeId,
            CodEstCivil = persona.CodEstCivil,
            CodInstrucao = persona.CodInstrucao,
            TiposangEnum = persona.TiposangEnum,
            Rg = persona.Rg,
            RgData = persona.RgData,
            RgCodEmissor = persona.RgCodEmissor,
            RgUf = persona.RgUf,
            Cnes = persona.Cnes,
            Ctps = persona.Ctps,
            CtpsSerie = persona.CtpsSerie,
            CtpsUf = persona.CtpsUf,
            CtpsData = persona.CtpsData,
            DataOpcao = persona.DataOpcao,
            CtpsDigital = persona.CtpsDigital,
            Titulo = persona.Titulo,
            TituloData = persona.TituloData,
            TituloZona = persona.TituloZona,
            TituloSecao = persona.TituloSecao,
            TituloFkcidade = persona.TituloFkcidade,
            Habilitacao = persona.Habilitacao,
            HabilitacaoCategEnum = persona.HabilitacaoCategEnum,
            HabilitacaoValidade = persona.HabilitacaoValidade,
            HabilitacaoEmissao = persona.HabilitacaoEmissao,
            DefFisica = persona.DefFisica,
            DefVisual = persona.DefVisual,
            DefAuditiva = persona.DefAuditiva,
            DefMental = persona.DefMental,
            DefIntelectual = persona.DefIntelectual,
            DefReabilitado = persona.DefReabilitado,
            DefCota = persona.DefCota,
            DefObservacao = persona.DefObservacao,
            TipoLogradouro = persona.TipoLogradouro,
            Logradouro = persona.Logradouro,
            Numero = persona.Numero,
            Complemento = persona.Complemento,
            Cep = persona.Cep,
            Bairro = persona.Bairro,
            MunicipioId = persona.MunicipioId,
            PontoReferencia = persona.PontoReferencia,
            CodBanco = persona.CodBanco,
            Agencia = persona.Agencia,
            Conta = persona.Conta,
            ContaOp = persona.ContaOp,
            ContaTipo = persona.ContaTipo,
            SyncBimestre = persona.SyncBimestre,
            ControleDataMigracao = persona.ControleDataMigracao,
            ControleUsuarioId = persona.ControleUsuarioId,
            ControleDataAlteracao = persona.ControleDataAlteracao,
            ControleVerificador = persona.ControleVerificador,
            ControleCadastradorId = persona.ControleCadastradorId,
            ControleDataCadastro = persona.ControleDataCadastro,
            RecadUserid = persona.RecadUserid,
            RecadData = persona.RecadData,
            RecadVersao = persona.RecadVersao,
            RecadStatus = persona.RecadStatus,
            OrdemFkorgao = persona.OrdemFkorgao,
            OrdemNumero = persona.OrdemNumero,
            OrdemEmissao = persona.OrdemEmissao,
            OrdemValidade = persona.OrdemValidade,
            OrdemObservacao = persona.OrdemObservacao,
            Uf = persona.Uf,
            DigitalOk = persona.DigitalOk,
            DigitalValor = persona.DigitalValor,
            DigitalImagem = persona.DigitalImagem,
            DigitalHstore01 = persona.DigitalHstore01
        };
    }
}
