namespace RecadastramentoApi.DTO;

public sealed class ManutencaoUpsertDto
{
    public long? id { get; set; }
    public int? fkrecadastramento { get; set; }
    public int? fkmanutencaobase { get; set; }
    public int? fkempregado { get; set; }
    public int? fkpersona { get; set; }
    public int? fkempresa_esocial { get; set; }
    public string? periodo { get; set; }
    public string? cod_folha { get; set; }
    public string? matricula { get; set; }
    public short? contrato { get; set; }
    public int? periodoinclusao_id { get; set; }
    public int? formadeadmissao_id { get; set; }
    public DateTime? data_concurso { get; set; }
    public int? cod_admissao { get; set; }
    public DateTime? data_admissao { get; set; }
    public short? tipo_admissao { get; set; }
    public DateTime? data_fimcontrato { get; set; }
    public DateTime? data_demissao { get; set; }
    public string? cod_desligamento { get; set; }
    public short? tipo_desligamento { get; set; }
    public string? regime_juridico { get; set; }
    public string? cod_vinculo { get; set; }
    public short? turno_enum { get; set; }
    public string? prev_privada { get; set; }
    public short? evento_previdencia { get; set; }
    public int? cod_previdencia { get; set; }
    public int? cod_categoria { get; set; }
    public int? cod_ocorrencia { get; set; }
    public DateTime? data_posse { get; set; }
    public string? observacao { get; set; }
    public DateTime? portaria_data { get; set; }
    public string? portaria_posse { get; set; }
    public string? matricula_anterior { get; set; }
    public DateTime? nomeacao_data { get; set; }
    public string? nomeacao_doc { get; set; }
    public short? nomeacao_enum { get; set; }
    public short? desconta_irrf { get; set; }
    public short? indicador_alvara { get; set; }
    public short? indicador_aprendizgravida { get; set; }
    public short? indicador_teletrabalho { get; set; }
    public short? indicador_trabalhointermitente { get; set; }
    public short? indicador_trabalhoparcial { get; set; }
    public string? codigo_examemedico { get; set; }
    public DateTime? data_examemedico { get; set; }
    public string? cnpj_laboratoio { get; set; }
    public string? crm_medico { get; set; }
    public string? crm_medico_uf { get; set; }
    public short? autorizado { get; set; }
    public int? autorizador_id { get; set; }
    public DateTime? autorizado_data { get; set; }
    public string? autorizado_obs { get; set; }
    public int? assesi { get; set; }
    public int? cod_situacao { get; set; }
    public decimal? gratificacao { get; set; }
    public string? cod_lotacao { get; set; }
    public string? cod_alocacao { get; set; }
    public int? formadeadmissaoexerc_id { get; set; }
    public string? cod_referencia_funcao { get; set; }
    public int? cod_cargo { get; set; }
    public decimal? salariobase { get; set; }
    public int? cod_cargo_contratual { get; set; }
    public decimal? salario_contratual { get; set; }
    public int? cod_cargo_area { get; set; }
    public int? cod_funcao { get; set; }
    public decimal? base_plantao { get; set; }
    public int? fkevento_sindicato { get; set; }
    public int? fkevento_associacao { get; set; }
    public short? fkevento_adictempserv { get; set; }
    public short? auxilio_transporte { get; set; }
    public int? fkevento_gratif { get; set; }
    public int? fkevento_adictemposervico { get; set; }
    public int? fkevento_previdencia { get; set; }
    public int? fkevento_titulacao { get; set; }
    public int? fkevento_planocarreira { get; set; }
    public short? frequencia_bool { get; set; }
    public short? plano_carreira { get; set; }
    public short? pc_titulo { get; set; }
    public short? especialferias_enum { get; set; }
    public short? especiallicenca_enum { get; set; }
    public short? sal13aniversario_enum { get; set; }
    public string? cpf_pararemessa { get; set; }
    public int? contaremessa_id { get; set; }
    public decimal? fgts { get; set; }
    public short? siope_segmento { get; set; }
    public short? siope_profinfantil { get; set; }
    public short? siope_mestrepedagogo { get; set; }
    public short? siope_tecnicopedagogo { get; set; }
    public short? siope_notoriosaber { get; set; }
    public short? siope_profgraduado { get; set; }
    public short? siope_psicologo { get; set; }
    public short? siope_servsocial { get; set; }
    public short? siope_outros { get; set; }
    public int? quinquenios_qtde { get; set; }
    public int? depend_irrf { get; set; }
    public int? depend_inss { get; set; }
    public int? dias { get; set; }
    public decimal? faltas { get; set; }
    public decimal? salario_bruto { get; set; }
    public decimal? descontos { get; set; }
    public decimal? salario_liquido { get; set; }
    public decimal? salario13_fracao { get; set; }
    public decimal? reserva_13sal { get; set; }
    public decimal? reserva_ferias { get; set; }
    public decimal? reserva_ferias1_3 { get; set; }
    public decimal? reserva_fgts40 { get; set; }
    public decimal? reserva_aviso { get; set; }
    public decimal? base_ferias { get; set; }
    public decimal? margem_consignavel { get; set; }
    public decimal? margem_consignavel_liq { get; set; }
    public short? ativo { get; set; }
    public short? status_enum { get; set; }
    public int? controle_usuario_id { get; set; }
    public DateTime? controle_data_migracao { get; set; }
    public DateTime? controle_data_alteracao { get; set; }
    public string? controle_verificador { get; set; }
    public int? controle_cadastrador_id { get; set; }
    public DateTime? controle_data_cadastro { get; set; }
    public int? recad_userid { get; set; }
    public DateTime? recad_data { get; set; }
    public int? recad_versao { get; set; }
    public int? recad_status { get; set; }
}
